Parameters:
  ServiceName:
    Type: String
  Environment:
    Type: String
    Default: prod
  ServiceURL:
    Type: String
  PhoneNumber:
    Type: String
    Default: ""
  VersionSHA:
    Type: String
    Default: ""
    Description: "Git commit SHA or version identifier for the Lambda code"

Conditions:
  HasPhone:
    Fn::Not: [!Equals [!Ref PhoneNumber, ""]]
  HasVersionSHA:
    Fn::Not: [!Equals [!Ref VersionSHA, ""]]

Resources:
  HealthCheckLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub kloudcover-public-${AWS::Region}-601394826940
        S3Key: !If 
          - HasVersionSHA
          - !Sub healthcheck/bootstrap-arm64-${VersionSHA}.zip
          - healthcheck/bootstrap-arm64.zip
      Description: !Sub 
        - "${ServiceName}-${Environment}-healthcheck${Suffix}"
        - Suffix: !If [HasVersionSHA, !Sub " - Version: ${VersionSHA}", ""]
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          METRIC_NAME: !Sub ${ServiceName}-${Environment}
          URL: !Sub ${ServiceURL}
          VERSION: !If [HasVersionSHA, !Ref VersionSHA, '1']
      Role: !GetAtt HealthCheckLambdaRole.Arn
      Handler: bootstrap
      Architectures:
        - arm64
      MemorySize: 128
      Runtime: provided.al2
      Timeout: 20

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt HealthCheckLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HealthCheckEvent.Arn

  HealthCheckEvent:
    Type: AWS::Events::Rule
    Properties:
      State: ENABLED
      Description: !Sub ${ServiceName}-${Environment}-healthcheck
      ScheduleExpression: rate(1 minute)
      Targets:
        - Id: !Sub ${ServiceName}-${Environment}-healthcheck
          Arn: !GetAtt HealthCheckLambda.Arn

  HealthCheckLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "CloudWatchMetrics"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"

  HealthAlertTopic:
    Type: AWS::SNS::Topic

  AlertSubscription:
    Condition: HasPhone
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref HealthAlertTopic
      Protocol: sms
      Endpoint: !Sub ${PhoneNumber}

  HealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref HealthAlertTopic
      AlarmName: !Sub ${ServiceName}-${Environment}-health
      MetricName: is-up
      Namespace: AppHealth
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Sub ${ServiceName}-${Environment}
